# Site settings
title: Great New Blog Title
author:
  name: Husne Dereli-Begue
  email: husnedereli@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
